import { Router } from 'express';
import { pool } from '../lib/db.js';
import { requireAuth } from '../lib/auth.js';
import { recalculateUserScore, recalculateContractorScore } from '../lib/score.js';
const router = Router(); router.use(requireAuth);
async function activeMember(userId) {
  const { rows } = await pool.query("SELECT 1 FROM memberships WHERE user_id=$1 AND status='ACTIVE'", [userId]);
  return Boolean(rows[0]);
}
router.get('/', async (req,res) => { const { rows } = await pool.query(`SELECT j.*, (SELECT count(*) FROM bids b WHERE b.job_id=j.id)::int AS bid_count FROM jobs j WHERE j.owner_id=$1 OR j.status='OPEN' ORDER BY j.created_at DESC`, [req.user.sub]); res.json({ jobs: rows }); });
router.post('/', async (req,res) => { const { title, description, location, budget = req.body.budget_min, startsAt, start_date } = req.body; if (!await activeMember(req.user.sub)) return res.status(403).json({ error:'Active membership required' }); if (!title || !description) return res.status(400).json({ error:'Title and description are required' }); const { rows } = await pool.query(`INSERT INTO jobs (owner_id,title,description,location,budget,starts_at) VALUES ($1,$2,$3,$4,$5,$6) RETURNING *`, [req.user.sub,title,description,location,budget,startsAt || start_date || null]); res.status(201).json({ job: rows[0] }); });
router.get('/:id/bids', async (req,res) => { const { rows } = await pool.query(`SELECT b.id,b.job_id,b.bidder_id,b.message,b.status,b.created_at,u.name AS bidder_name,u.score AS bidder_score FROM bids b JOIN users u ON u.id=b.bidder_id WHERE b.job_id=$1 AND (b.bidder_id=$2 OR EXISTS (SELECT 1 FROM jobs j WHERE j.id=b.job_id AND j.owner_id=$2)) ORDER BY b.created_at DESC`, [req.params.id, req.user.sub]); res.json({ bids: rows }); });
router.post('/:id/bids', async (req,res) => { if (!await activeMember(req.user.sub)) return res.status(403).json({ error:'Active membership required' }); if (!req.body.amount) return res.status(400).json({error:'Amount is required'}); const { rows } = await pool.query(`INSERT INTO bids (job_id,bidder_id,amount,message) SELECT $1,$2,$3,$4 WHERE EXISTS (SELECT 1 FROM jobs WHERE id=$1 AND status='OPEN' AND owner_id<>$2) RETURNING id,job_id,bidder_id,message,status,created_at`,[req.params.id,req.user.sub,req.body.amount,req.body.message || '']); rows[0] ? res.status(201).json({bid:rows[0]}) : res.status(409).json({error:'Job is not open or cannot bid on own job'}); });
router.patch('/bids/:id/status', async (req,res) => { if (req.body.status !== 'ACCEPTED') return res.status(400).json({error:'Only awarding a bid is supported here'}); const { rows } = await pool.query(`UPDATE bids b SET status='ACCEPTED',updated_at=now() FROM jobs j JOIN users owner ON owner.id=j.owner_id WHERE b.id=$2 AND j.id=b.job_id AND j.owner_id=$1 AND owner.role='CONTRACTOR' AND j.status='OPEN' RETURNING b.*`,[req.user.sub,req.params.id]); if (!rows[0]) return res.status(403).json({error:'Only the authorized organization administrator can award an open job'}); await pool.query(`UPDATE jobs SET status='AWARDED',updated_at=now() WHERE id=$1 AND status='OPEN'`,[rows[0].job_id]); await recalculateUserScore(rows[0].bidder_id); await recalculateContractorScore(req.user.sub); res.json({bid:{id:rows[0].id,job_id:rows[0].job_id,status:rows[0].status}}); });
router.patch('/:id/status', async (req,res) => { const transitions={OPEN:['CANCELLED'],AWARDED:['IN_PROGRESS','CANCELLED'],IN_PROGRESS:['COMPLETED','CANCELLED']}; const current=(await pool.query('SELECT status FROM jobs WHERE id=$1 AND owner_id=$2',[req.params.id,req.user.sub])).rows[0]; if (!current || !transitions[current.status]?.includes(req.body.status)) return res.status(409).json({error:'Invalid job lifecycle transition'}); const { rows } = await pool.query(`UPDATE jobs SET status=$1,updated_at=now() WHERE id=$2 AND owner_id=$3 RETURNING *`,[req.body.status,req.params.id,req.user.sub]); if (req.body.status === 'COMPLETED') { const awarded=(await pool.query("SELECT bidder_id FROM bids WHERE job_id=$1 AND status='ACCEPTED'",[req.params.id])).rows[0]; if (awarded) { await recalculateUserScore(awarded.bidder_id); await recalculateContractorScore(req.user.sub); } } res.json({job:rows[0]}); });
router.post('/:id/ratings', async (req,res) => { const score=Number(req.body.score); if (!Number.isFinite(score) || score < 0 || score > 5 || !req.body.ratedUserId) return res.status(400).json({error:'A score from 0 to 5 and ratedUserId are required'}); try { const { rows } = await pool.query(`INSERT INTO ratings(job_id,rater_id,rated_user_id,score) SELECT $1,$2,$3,$4 WHERE EXISTS (SELECT 1 FROM jobs WHERE id=$1 AND status='COMPLETED') RETURNING *`,[req.params.id,req.user.sub,req.body.ratedUserId,score]); if (!rows[0]) return res.status(409).json({error:'Job must be completed'}); await recalculateUserScore(req.body.ratedUserId); res.status(201).json({rating:rows[0]}); } catch (e) { if (e.code === '23505') return res.status(409).json({error:'Rating already submitted'}); throw e; } });
export default router;
