CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email text NOT NULL UNIQUE,
  password_hash text NOT NULL, display_name text NOT NULL, username text UNIQUE,
  email_verified_at timestamptz, phone_verified_at timestamptz, force_password_change boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS roles (id serial PRIMARY KEY, name text NOT NULL UNIQUE);
INSERT INTO roles(name) VALUES ('WORKER'), ('CONTRACTOR'), ('ADMIN'), ('SUPER_ADMIN') ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS user_roles (user_id uuid REFERENCES users(id) ON DELETE CASCADE, role_id integer REFERENCES roles(id), PRIMARY KEY(user_id, role_id));
CREATE TABLE IF NOT EXISTS sessions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, token_hash text NOT NULL UNIQUE, expires_at timestamptz NOT NULL, revoked_at timestamptz, mfa_verified_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS companies (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, created_by uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS company_memberships (company_id uuid REFERENCES companies(id) ON DELETE CASCADE, user_id uuid REFERENCES users(id) ON DELETE CASCADE, role text NOT NULL DEFAULT 'MEMBER', created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(company_id,user_id));
CREATE TABLE IF NOT EXISTS work_passports (user_id uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, trade text, skills jsonb NOT NULL DEFAULT '[]', years_experience integer, service_area text, profile_summary text, verification_status text NOT NULL DEFAULT 'PENDING', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS work_history (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, company_id uuid REFERENCES companies(id), title text, details text, started_on date, ended_on date, status text NOT NULL DEFAULT 'SELF_REPORTED', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS evidence (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), type text NOT NULL, metadata jsonb NOT NULL DEFAULT '{}', status text NOT NULL DEFAULT 'PENDING', submitter uuid REFERENCES users(id), reviewer uuid REFERENCES users(id), submitted_at timestamptz NOT NULL DEFAULT now(), reviewed_at timestamptz, notes text);
CREATE TABLE IF NOT EXISTS private_files (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), evidence_id uuid REFERENCES evidence(id) ON DELETE CASCADE, object_key text NOT NULL UNIQUE, mime_type text NOT NULL, size_bytes bigint NOT NULL, malware_status text NOT NULL DEFAULT 'PENDING', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS verification_records (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), evidence_id uuid REFERENCES evidence(id) ON DELETE CASCADE, reviewer uuid REFERENCES users(id), status text NOT NULL, reason text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS jobs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES companies(id), created_by uuid NOT NULL REFERENCES users(id), title text NOT NULL, trade text NOT NULL, description text, location text, budget numeric, budget_type text, desired_start_date date, estimated_duration text, requirements jsonb NOT NULL DEFAULT '[]', verification_requirements jsonb NOT NULL DEFAULT '[]', status text NOT NULL DEFAULT 'DRAFT', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS bids (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), job_id uuid NOT NULL REFERENCES jobs(id) ON DELETE CASCADE, worker_id uuid NOT NULL REFERENCES users(id), amount numeric NOT NULL, message text, estimated_duration text, status text NOT NULL DEFAULT 'SUBMITTED', created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(job_id,worker_id));
CREATE TABLE IF NOT EXISTS job_awards (job_id uuid PRIMARY KEY REFERENCES jobs(id) ON DELETE CASCADE, bid_id uuid NOT NULL UNIQUE REFERENCES bids(id), awarded_by uuid NOT NULL REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS job_completions (job_id uuid PRIMARY KEY REFERENCES jobs(id) ON DELETE CASCADE, worker_confirmed_at timestamptz, contractor_confirmed_at timestamptz, disputed_at timestamptz);
CREATE TABLE IF NOT EXISTS worker_feedback (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), job_id uuid NOT NULL REFERENCES jobs(id), worker_id uuid NOT NULL REFERENCES users(id), contractor_id uuid NOT NULL REFERENCES users(id), quality integer, reliability integer, communication integer, schedule_performance integer, scope_execution integer, would_hire_again boolean, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(job_id,contractor_id));
CREATE TABLE IF NOT EXISTS contractor_feedback (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), job_id uuid NOT NULL REFERENCES jobs(id), worker_id uuid NOT NULL REFERENCES users(id), company_id uuid NOT NULL REFERENCES companies(id), payment_reliability integer, scope_accuracy integer, project_readiness integer, communication integer, schedule_organization integer, would_work_again boolean, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(job_id,worker_id));
CREATE TABLE IF NOT EXISTS work_score_snapshots (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), score numeric, status text NOT NULL, factors jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS contractor_score_snapshots (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES companies(id), score numeric, status text NOT NULL, factors jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS subscriptions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), stripe_customer_id text, stripe_subscription_id text UNIQUE, status text NOT NULL DEFAULT 'INCOMPLETE', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS notifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, type text NOT NULL, payload jsonb NOT NULL DEFAULT '{}', read_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS disputes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), job_id uuid NOT NULL REFERENCES jobs(id), opened_by uuid NOT NULL REFERENCES users(id), reason text NOT NULL, status text NOT NULL DEFAULT 'OPEN', resolution text, reviewer uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), resolved_at timestamptz);
CREATE TABLE IF NOT EXISTS audit_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), actor_id uuid REFERENCES users(id), action text NOT NULL, entity_type text NOT NULL, entity_id uuid, metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS admin_mfa (user_id uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, secret text NOT NULL, enabled_at timestamptz, verified_at timestamptz);
CREATE INDEX IF NOT EXISTS jobs_company_status_idx ON jobs(company_id,status);
CREATE INDEX IF NOT EXISTS bids_job_idx ON bids(job_id);
CREATE INDEX IF NOT EXISTS evidence_status_idx ON evidence(status);
